### ISSUE TITLE
Link local being used as ip6address

### ISSUE THREAD

**Issue by vegardx** [chef/ohai#643]
When detecting IP-addresses and the node doens't have a IPv6-address with global scope it takes the link local address and uses that as ip6address. I don't think this is intended to happen, ref. #244.

```
chef_packages:
  chef:
    chef_root: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib
    version:   12.5.1
  ohai:
    ohai_root: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.7.0/lib/ohai
    version:   8.7.0
```

```
fqdn:              chef-test.example.test
hostname:          chef-test
idletime:          14 days 06 hours 50 minutes 38 seconds
idletime_seconds:  1234238
init_package:      systemd
ip6address:        fe80::216:37ff:fe8b:6c25
ipaddress:         172.16.0.225
```

```
network:
  default_gateway:   172.16.0.1
  default_interface: eth0
  interfaces:
    eth0:
      addresses:
        00:16:37:8B:6C:25:
          family: lladdr
        172.16.0.225:
          broadcast: 172.16.0.255
          family:    inet
          netmask:   255.255.255.0
          prefixlen: 24
          scope:     Global
        fe80::216:37ff:fe8b:6c25:
          family:    inet6
          prefixlen: 64
          scope:     Link
      arp:
        172.16.0.1:   24:a4:3c:06:09:89
        172.16.0.153: 00:25:00:ee:8b:3c
        172.16.0.228: 00:16:37:c9:e8:9e
      encapsulation: Ethernet
      flags:
        BROADCAST
        MULTICAST
        UP
        LOWER_UP
      mtu:           1500
      number:        0
      routes:
        destination: default
        family:      inet
        via:         172.16.0.1

        destination: 172.16.0.0/24
        family:      inet
        proto:       kernel
        scope:       link
        src:         172.16.0.225

        destination: fe80::/64
        family:      inet6
        metric:      256
        proto:       kernel
      state:         up
      type:          eth
    lo:
      addresses:
        127.0.0.1:
          family:    inet
          netmask:   255.0.0.0
          prefixlen: 8
          scope:     Node
        ::1:
          family:    inet6
          prefixlen: 128
          scope:     Node
      encapsulation: Loopback
      flags:
        LOOPBACK
        UP
        LOWER_UP
      mtu:           65536
      state:         unknown
```
