### ISSUE TITLE
packages provider inconsistent results

### ISSUE THREAD

**Issue by glensc** [chef/ohai#819]
## Description

i find debian packages listing inconsistent with one that rpm provides.

 - rpm system has "release" portion
 - deb system "release" is included in "version" portion
 - some deb package names contain archtecture `zlib1g:amd64`
 - debian versions also include "epoch"

ideally i'd see:
 - rpm systems include extra `arch` tag
 - deb systems include `arch` tag, extract it from `name` if needed
 - deb systems include `release` tag
 - epoch moved to extra tag

# examples from systems

rpm system:
```
# knife node show fqdn -a packages
pld:
  packages:
    glibc-misc:
      release: 21
      version: 2.3.6
    glibc64:
      release: 21
      version: 2.3.6
```
debian-7 system:
```
# knife node show fqdn -a packages
debian:
  packages:
    acpi:
      version: 1.6-1
    zlib1g:amd64:
      version: 1:1.2.7.dfsg-13
```
## Ohai Version

Ohai: 7.4.0, but packages is taken from ohai that was merged in v8.9.0
18ae02f5e4dc0ff096271f39fd1a970a0adc52c7

## Platform Version

Debian 7
